version: 0.2
phases:
  install:
    commands:
      - yum update -y
      - sudo yum install java-1.8.0-openjdk -y
      - sudo wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
      - sudo sed -i s/\$releasever/6/g /etc/yum.repos.d/epel-apache-maven.repo
      - yum install -y apache-maven
      - mvn --version
      - java --version
    runtime-version:
      #java: /usr/lib/jvm/java-17-amazon-corretto.x86_64
    
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn clean test 
artifacts:
  files:
    - /target/deliziahr-authentication-service-0.0.1-SNAPSHOT.jar
