version: 0.2
phases:
  install:
    commands:
      - sudo apt-add-repository ppa:linuxuprising/java
      - sudo apt-get update -y
      - sudo apt-get install -y curl
      - sudo curl -O https://download.java.net/java/GA/jdk13/5b8a42f3905b406298b72d750b6919f6/33/GPL/openjdk-13_linux-x64_bin.tar.gz
      - sudo tar xvf openjdk-13_linux-x64_bin.tar.gz
      - sudo mv jdk-13 /opt/
      - sudo tee /etc/profile.d/jdk13.sh <<EOF        export JAVA_HOME=/opt/jdk-13        export PATH=\$PATH:\$JAVA_HOME/bin         EOF
      - sudo source /etc/profile.d/jdk13.sh
      - sudo apt-get install maven -y
      - sudo java --version
      
       
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - sudo mvn install 
artifacts:
  files:
    - /target/deliziahr-authentication-service-0.0.1-SNAPSHOT.jar
