version: 0.2
phases:
  install:
    commands:
      - sudo apt-add-repository ppa:linuxuprising/java
      - sudo apt-get update -y
      - sudo apt install openjdk-14-jdk
      - sudo apt install maven -y
      - sudo java --version
      
       
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - sudo mvn install 
artifacts:
  files:
    - /target/deliziahr-authentication-service-0.0.1-SNAPSHOT.jar
