version: 0.2
phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:openjdk-r/ppa
      - apt-get update -y
      - apt-get install -y openjdk-13-jdk
      - apt-get install -y maven
      - java -version
      
       
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install 
artifacts:
  files:
    - /target/deliziahr-authentication-service-0.0.1-SNAPSHOT.jar
